version: "3.8"
services:
  nginx:
    image: nginx:latest
    networks:
      - "animal-net"  
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "front-end"
  front-end: 
    image: numphries/animal-frontend:v2
    build: ./front-end
    networks:
      - "animal-net"
    depends_on:
      - "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  animal-api:
    image: numphries/animal-api:latest
    build: ./animal-api
    networks:
      - "animal-net"
  noise-api:
    image: numphries/noise-api:latest
    build: ./noise-api
    networks:
      - "animal-net"
  mysql:
    image: numphries/animal-noise-db:latest
    build: ./db
    volumes:
      - type: volume
        source: animal-vol
        target: /var/lib/mysql
    networks:
      - "animal-net"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: animal_db
networks:
  animal-net:
volumes:
  animal-vol:
    #driver: overlay